name = "dailytally2"
main = "src/worker.js"
compatibility_date = "2026-04-27"
compatibility_flags = [ "nodejs_compat" ]

[vars]
AUTHENTIK_ISSUER = "https://auth.showway.biz/application/o/dailytally2/"
AUTHENTIK_CLIENT_ID = "zaLBuoRHriNUqtrRQD7KYXYaVVcUyOHEdvp2uT9y"
REPORT_REMOTE_SUBMIT = "true"
TENDO_ACCOUNT = "shigurenoki"
REPORT_NOTIFY_FROM = "Dailytally2 <notify@showway.biz>"
MASTERS_URL = "https://osystem-masters.kusanaginoturugi.workers.dev"
# REPORT_ONLINE_FORM_URL = ""
# REPORT_ONLINE_FILE_FIELD = "up_file[]"

[triggers]
crons = [ "*/15 * * * *" ]

[browser]
binding = "BROWSER"

[assets]
directory = "./public"
binding = "ASSETS"
run_worker_first = [ "/*" ]

[[d1_databases]]
binding = "DB"
database_name = "dailytally2"
database_id = "ac0f9340-c703-40fd-b816-6063f16e2382"
migrations_dir = "migrations"

[observability]
enabled = false
head_sampling_rate = 1

[observability.logs]
enabled = true
head_sampling_rate = 1
persist = true
invocation_logs = true

[observability.traces]
enabled = false
persist = true
head_sampling_rate = 1
